### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByClassName' of null

### ISSUE THREAD

**Issue by ArnaudLoos** [tumpio/gmscripts#1]
Extension: DuckDuckGo_Extended.
Chrome Inspector showing the following error "Uncaught TypeError: Cannot read property 'getElementsByClassName' of null" from script.js line 349. Indeed document.getElementById("header_button_menu") does return null.

**Comment by Martii** [comment]
@tumpio 

> I don't know why the web hook doesn't work now.

There was one point where certain scripts got unsync'd... however it should be fixed now. All you need to do is reimport it via the GitHub import section... that will retain your stats... this is assuming you still have the webhook enabled here on GH.

Btw I know for sure that `egoogle.user.js` is [out of sync](https://openuserjs.org/scripts/tumpio/Endless_Google) right now... so you should just be able to reimport that and if all goes well you should be good to go.

Please let me know if you are having issues so I can try to assist you. :)

**Comment by tumpio** [comment]
@Martii 
Thank you for letting me know! I did as you suggested. The content type for the webhook was application/json. I changed it as well. Now I'll have to work on my scripts to test the hook! :+1: 

Have a great week! :)

**Comment by Martii** [comment]
@tumpio 
No problem... I do suggest in the future that you increment `@version` though... makes it a little easier for everyone to get notified of updates as well as the specific tracking on what happened way back then. :) 

I've manually rechecked your entire account and reset a few things from all the fixes we've done since those times.

Enjoy,
OUJS Admin
